version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    # Only for travis-ci, do not name test container in dockerhub
    container_name: sut
    depends_on:
      - frappe_db
      - frappe_app
      - frappe_web
      - frappe_scheduler
      - frappe_worker_default
      - frappe_worker_long
      - frappe_worker_short
      - frappe_socketio
      - frappe_redis_cache
      - frappe_redis_queue
      - frappe_redis_socketio
    environment:
      # Container setup
      - NODE_TYPE=test
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_app:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_app
    command: app
    #restart: always
    ports:
      - 8000:8000
    depends_on:
      - frappe_db
    links:
      - frappe_db
    environment:
      # Docker setup
      - DOCKER_DB_ALLOWED_HOSTS=
      # Frappe setup
      - FRAPPE_APP_INIT=frappe
      - FRAPPE_DEFAULT_PROTOCOL=http://
      - FRAPPE_DEFAULT_SITE=${FRAPPE_SITE}
      - FRAPPE_LOGGING=1
      #- ADMIN_USER=Administrator
      - ADMIN_PASSWORD=${FRAPPE_ADMIN_PWD}
      - ENCRYPTION_KEY=${FRAPPE_ENCRYPTION_KEY}
      # Database setup
      - DB_TYPE=mariadb
      - DB_HOST=frappe_db
      - DB_PORT=3306
      - DB_NAME=${FRAPPE_DB_NAME}
      - DB_PASSWORD=${FRAPPE_DB_PWD}
      - DB_ROOT_PASSWORD=${FRAPPE_DB_ROOT_PWD}
      # Mail setup
      - MAIL_HOST=${FRAPPE_MAIL_HOST}
      - MAIL_PORT=587
      - MAIL_USE_SSL=tls
      - MAIL_LOGIN=${FRAPPE_SMTP_USER}
      - MAIL_PASSWORD=${FRAPPE_SMTP_PWD}
      # Redis setup
      - REDIS_CACHE_HOST=frappe_redis_cache
      - REDIS_QUEUE_HOST=frappe_redis_queue
      - REDIS_SOCKETIO_HOST=frappe_redis_socketio
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /srv/erpnext/frappe/logs:/home/frappe/frappe-bench/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_web:
    image: nginx:alpine
    container_name: frappe_web
    #restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    volumes_from:
      - frappe_app
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    links:
      - frappe_app
      - frappe_socketio

  frappe_db:
    image: mariadb:10
    container_name: frappe_db
    #restart: always
    command: --character_set_client=utf8 --bind-address=0.0.0.0 --character-set-client-handshake=FALSE --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode="ALLOW_INVALID_DATES"
    environment:
      - MYSQL_ROOT_PASSWORD=${FRAPPE_DB_ROOT_PWD}
      # Following parameters are not needed with Frappe 12 or higher since it will create DB itself
      - MYSQL_DATABASE=${FRAPPE_DB_NAME}
      - MYSQL_USER=${FRAPPE_DB_NAME}
      - MYSQL_PASSWORD=${FRAPPE_DB_PWD}
    volumes:
      - /srv/erpnext/db:/var/lib/mysql

  frappe_scheduler:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_scheduler
    command: scheduler
    #restart: always
    depends_on:
      - frappe_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_worker_default:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_worker_default
    command: worker-default
    #restart: always
    depends_on:
      - frappe_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_worker_long:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_worker_long
    command: worker-long
    #restart: always
    depends_on:
      - frappe_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_worker_short:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_worker_short
    command: worker-short
    #restart: always
    depends_on:
      - frappe_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_socketio:
    # For development or CI, build from local Dockerfile
    build: ./
    # For production, download prebuilt image
    #image: monogramm:docker-frappe:develop
    container_name: frappe_socketio
    command: node-socketio
    #restart: always
    ports:
      - 3000:3000
    depends_on:
      - frappe_app
    environment:
      # Docker setup
      - DOCKER_APPS_TIMEOUT=900
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  frappe_redis_cache:
    image: redis:alpine
    container_name: frappe_redis_cache
    #restart: always
    volumes:
      - ./services/erpnext/conf/redis_cache.conf:/etc/conf.d/redis.conf:ro
    command: ["redis-server","/etc/conf.d/redis.conf"]

  frappe_redis_queue:
    image: redis:alpine
    container_name: frappe_redis_queue
    #restart: always

  frappe_redis_socketio:
    image: redis:alpine
    container_name: frappe_redis_socketio
    #restart: always
